import { Metadata } from "next/dist/lib/metadata/types/metadata-interface";
import TestSupabaseAuth from "./components/TestSupabaseAuth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <TestSupabaseAuth />
    </main>
  );
}
